- build.gradle
- buildspec.yml
- buildspec_publish_to_sar.yml
- template.yaml
Updated to Java 11, changed sar name metadata (name) in template.yaml. Removed cors settings from template parameters
> Np 605 update sar

- build.gradle
- src/main/java/no/unit/nva/cristin/projects/PresentationConverter.java
- src/test/java/no/unit/nva/cristin/projects/FetchCristinProjectsTest.java
- src/test/java/no/unit/nva/cristin/projects/TestPairProvider.java
- src/test/resources/api_query_response.json
Fixes the missing funder information, additionally:
- Adds some testing because the actual test for the data was missing
- bumped versions on Jackson and JUnit
> Np 2271 fix funding title

- LICENSE
- README.md
- build.gradle
- src/main/java/no/unit/nva/cristin/projects/Affiliation.java
- src/main/java/no/unit/nva/cristin/projects/CristinApiClient.java
- src/main/java/no/unit/nva/cristin/projects/FetchCristinProjects.java
- src/main/java/no/unit/nva/cristin/projects/FundingSource.java
- src/main/java/no/unit/nva/cristin/projects/Institution.java
- src/main/java/no/unit/nva/cristin/projects/Interaction.java
- src/main/java/no/unit/nva/cristin/projects/JsonPropertyNames.java
- src/main/java/no/unit/nva/cristin/projects/Organization.java
- src/main/java/no/unit/nva/cristin/projects/Person.java
- src/main/java/no/unit/nva/cristin/projects/PresentationConverter.java
- src/main/java/no/unit/nva/cristin/projects/Project.java
- src/main/java/no/unit/nva/cristin/projects/ProjectPresentation.java
- src/main/java/no/unit/nva/cristin/projects/Role.java
- src/main/java/no/unit/nva/cristin/projects/Unit.java
- src/test/java/no/unit/nva/cristin/projects/CristinApiClientStub.java
- src/test/java/no/unit/nva/cristin/projects/FetchCristinProjectsTest.java
- src/test/java/no/unit/nva/cristin/projects/TestPairProvider.java
- src/test/resources/api_query_response.json
- src/test/resources/cristinGetProjectResponse.json
- template.yaml
Just first step, will refactor model classes more in later work
Extracted method for enriching projects. Still complains about using unneeded local variable
> NP-2157: Initial change from Gson to Jackson

- src/main/java/no/unit/nva/cristin/projects/CristinApiClient.java
- src/main/resources/log4j2.xml
> NP-2296: Add Log4j config file

- template.yaml
> NP-2515: Removed authorizers

- src/main/java/no/unit/nva/cristin/projects/CristinApiClient.java
- src/main/java/no/unit/nva/cristin/projects/NvaProjectBuilder.java
- src/main/java/no/unit/nva/cristin/projects/UriUtils.java
- src/main/java/no/unit/nva/cristin/projects/model/cristin/CristinProject.java
- src/test/java/no/unit/nva/cristin/projects/FetchCristinProjectsTest.java
- src/test/resources/api_query_response.json
- src/test/resources/api_query_response_no_projects_found.json
- src/test/resources/api_response_non_enriched_projects.json
A small PR but there were no other modeling logic in CristinApiClient
> Np 2538 move transformation logic

- src/main/java/no/unit/nva/cristin/projects/FetchCristinProjects.java
- src/main/java/no/unit/nva/cristin/projects/UriUtils.java
- src/test/java/no/unit/nva/cristin/projects/FetchCristinProjectsTest.java
Replaces spaces with + symbol according to W3C spec
> NP-2660: Title with whitespace now working

- build.gradle
- src/main/java/no/unit/nva/cristin/projects/NvaProjectBuilder.java
- src/test/resources/api_query_response.json
- src/test/resources/api_response_get_project_with_missing_fields.json
- src/test/resources/api_response_non_enriched_projects.json
- src/test/resources/api_response_one_cristin_project_to_nva_project.json
Updated nva commons version to latest
Updated test files
> NP-2679: Added mapping of language codes

- build.gradle
- src/main/java/no/unit/nva/cristin/projects/Constants.java
- src/main/java/no/unit/nva/cristin/projects/CristinApiClient.java
- src/main/java/no/unit/nva/cristin/projects/NvaProjectBuilder.java
- src/main/java/no/unit/nva/cristin/projects/ProjectsWrapper.java
- src/main/java/no/unit/nva/cristin/projects/UriUtils.java
- template.yaml
Refactored code to comply with new changes in cfn template
Set default parameters for simplified testing and deployment
> NP-2280: Changed cfn template from hardcoded values to using parameters

- cristin-commons/src/main/java/no/unit/nva/cristin/common/ErrorMessages.java
- cristin-commons/src/main/java/no/unit/nva/cristin/common/Utils.java
- cristin-commons/src/main/java/no/unit/nva/cristin/model/Constants.java
- cristin-person/src/main/java/no/unit/nva/cristin/person/client/CristinPersonApiClient.java
- cristin-person/src/main/java/no/unit/nva/cristin/person/client/CristinPersonQuery.java
- cristin-person/src/main/java/no/unit/nva/cristin/person/handler/FetchCristinPersonHandler.java
- cristin-person/src/test/java/no/unit/nva/cristin/person/handler/FetchCristinPersonHandlerTest.java
A little skeptical about how to set URI to cristin test instance, as orcid fetch is not in cristin production yet
> Np 2819 fetch person from orcid

- cristin-person/src/main/java/no/unit/nva/cristin/person/handler/ListCristinOrganizationPersonsHandler.java
- cristin-person/src/test/java/no/unit/nva/cristin/person/handler/ListCristinOrganizationPersonsHandlerTest.java
- cristin-person/src/test/java/no/unit/nva/cristin/person/handler/personOrganization.feature
- docs/cristin-proxy-swagger.yaml
- template.yaml
PR to verify definition of request and response formats, dummy handler implementation
> Np 4303 extend person query api

- cristin-commons/src/main/java/no/unit/nva/cristin/common/ErrorMessages.java
- cristin-commons/src/main/java/no/unit/nva/cristin/common/Utils.java
- cristin-commons/src/main/java/no/unit/nva/cristin/model/Constants.java
- cristin-person/src/main/java/no/unit/nva/cristin/person/client/DeletePersonEmploymentClient.java
- cristin-person/src/main/java/no/unit/nva/cristin/person/employment/query/QueryPersonEmploymentHandler.java
- cristin-person/src/main/java/no/unit/nva/cristin/person/handler/DeletePersonEmploymentHandler.java
- cristin-person/src/main/java/no/unit/nva/cristin/person/institution/common/PersonInstitutionInfoHandler.java
- cristin-person/src/main/java/no/unit/nva/cristin/person/institution/fetch/FetchPersonInstitutionInfoHandler.java
- cristin-person/src/main/java/no/unit/nva/cristin/person/institution/update/UpdatePersonInstitutionInfoHandler.java
- cristin-person/src/main/java/no/unit/nva/cristin/person/update/UpdateCristinPersonHandler.java
- cristin-person/src/test/java/no/unit/nva/cristin/person/employment/query/QueryPersonEmploymentHandlerTest.java
- cristin-person/src/test/java/no/unit/nva/cristin/person/employment/query/personEmploymentQuery.feature
- cristin-person/src/test/java/no/unit/nva/cristin/person/institution/fetch/FetchPersonInstitutionInfoHandlerTest.java
- cristin-person/src/test/java/no/unit/nva/cristin/person/institution/fetch/personInstitutionInfoFetch.feature
- cristin-person/src/test/java/no/unit/nva/cristin/person/institution/update/personInstitutionInfoUpdate.feature
- cristin-person/src/test/java/no/unit/nva/cristin/person/update/UpdateCristinPersonHandlerTest.java
- docs/cristin-proxy-swagger.yaml
- template.yaml
Handler skeleton setup, some common parameter verification and error handling
> Np 4298 delete affiliation - initial

- .github/workflows/karate.yml
- cristin-commons/src/main/java/no/unit/nva/cristin/common/client/CristinAuthenticator.java
- cristin-commons/src/main/java/no/unit/nva/utils/AccessUtils.java
- cristin-project/src/main/java/no/unit/nva/cristin/projects/UpdateCristinProjectHandler.java
- cristin-project/src/test/java/no/unit/nva/cristin/projects/FetchCristinProjectsTest.java
- cristin-project/src/test/java/no/unit/nva/cristin/projects/UpdateCristinProjectHandlerTest.java
- docs/cristin-proxy-swagger.yaml
- samconfig.toml
- template.yaml
Open API specification with samples and AWS Template for PATCH project  service
> Np 9065 project patch definitions

- cristin-commons/src/main/java/no/unit/nva/utils/PatchValidator.java
- cristin-project/src/main/java/no/unit/nva/cristin/projects/CristinApiClient.java
- cristin-project/src/main/java/no/unit/nva/cristin/projects/CristinProjectPatchJsonCreator.java
- cristin-project/src/main/java/no/unit/nva/cristin/projects/ProjectPatchValidator.java
- cristin-project/src/main/java/no/unit/nva/cristin/projects/UpdateCristinApiClient.java
- cristin-project/src/main/java/no/unit/nva/cristin/projects/UpdateCristinProjectHandler.java
- cristin-project/src/test/java/no/unit/nva/cristin/projects/UpdateCristinProjectHandlerTest.java
- docs/cristin-proxy-swagger.yaml
Update of parts of project in Cristin, filelds updated are title, contributors, coordinating_institution, language, start_date, end_date
> Np 9071 update cristin api client

- cristin-commons/src/main/java/no/unit/nva/cristin/common/client/ApiClient.java
- cristin-person/src/main/java/no/unit/nva/cristin/person/client/CristinOrganizationPersonsClient.java
- cristin-person/src/main/java/no/unit/nva/cristin/person/client/CristinPersonApiClient.java
- cristin-person/src/main/java/no/unit/nva/cristin/person/handler/ListCristinOrganizationPersonsHandler.java
- cristin-person/src/test/java/no/unit/nva/cristin/person/handler/ListCristinOrganizationPersonsHandlerTest.java
- template.yaml
Added authorization to list-organization-persons rest endpoint, tiny refactor using vars, added AWS right to read secret for lambda
> Added authorization to list-organization-persons endpoint

- cristin-commons/src/main/java/no/unit/nva/cristin/common/Utils.java
- cristin-commons/src/main/java/no/unit/nva/utils/AccessUtils.java
- cristin-person/src/main/java/no/unit/nva/cristin/person/employment/create/CreatePersonEmploymentHandler.java
- cristin-person/src/test/java/no/unit/nva/cristin/person/create/CreateCristinPersonHandlerTest.java
- cristin-person/src/test/java/no/unit/nva/cristin/person/employment/create/CreatePersonEmploymentHandlerTest.java
- cristin-person/src/test/java/no/unit/nva/cristin/person/update/UpdateCristinPersonHandlerTest.java
App admin only full access on creation of one employment
> NP-14998: Restrict app admin

- cristin-project/src/main/java/no/unit/nva/cristin/projects/create/CreateCristinProjectValidator.java
- cristin-project/src/test/java/no/unit/nva/cristin/projects/create/CreateCristinProjectHandlerTest.java
- cristin-project/src/test/java/no/unit/nva/cristin/projects/create/createProject.feature
errorMessage now contains hint of what happened.
> https://unit.atlassian.net/browse/NP-29836

- cristin-project/src/main/java/no/unit/nva/cristin/projects/model/cristin/CristinClinicalTrialPhaseBuilder.java
- cristin-project/src/main/java/no/unit/nva/cristin/projects/model/cristin/CristinHealthProjectTypeBuilder.java
- cristin-project/src/main/java/no/unit/nva/cristin/projects/model/cristin/CristinProjectBuilder.java
- cristin-project/src/main/java/no/unit/nva/cristin/projects/model/nva/ClinicalTrialPhase.java
- cristin-project/src/main/java/no/unit/nva/cristin/projects/model/nva/ClinicalTrialPhaseBuilder.java
- cristin-project/src/main/java/no/unit/nva/cristin/projects/model/nva/EnumBuilder.java
- cristin-project/src/main/java/no/unit/nva/cristin/projects/model/nva/HealthProjectType.java
- cristin-project/src/main/java/no/unit/nva/cristin/projects/model/nva/NvaProjectBuilder.java
- cristin-project/src/test/java/no/unit/nva/cristin/projects/RandomProjectDataGenerator.java
- cristin-project/src/test/java/no/unit/nva/cristin/projects/create/CreateCristinProjectHandlerTest.java
- cristin-project/src/test/java/no/unit/nva/cristin/projects/create/createSampleProject.feature
- cristin-project/src/test/java/no/unit/nva/cristin/projects/fetch/project.feature
- cristin-project/src/test/resources/api_query_response_with_funding.json
- cristin-project/src/test/resources/api_request_one_nva_project.json
- cristin-project/src/test/resources/api_response_one_cristin_project_to_nva_project_with_funding.json
- docs/cristin-proxy-swagger.yaml
Need some feedback on naming and structure. This is currently WiP
> Np 16247 decouple health fields from impl

- cristin-commons/src/main/java/no/unit/nva/cristin/common/Utils.java
- cristin-commons/src/main/java/no/unit/nva/cristin/model/Constants.java
- cristin-project/src/main/java/no/unit/nva/cristin/projects/common/CristinQuery.java
- cristin-project/src/main/java/no/unit/nva/cristin/projects/common/CristinQueryBuilder.java
- cristin-project/src/test/java/no/unit/nva/cristin/projects/query/QueryCristinProjectHandlerTest.java
> NP-41111-cristin-proxy-norwegian-special

- cristin-person/src/main/java/no/unit/nva/cristin/person/client/CristinOrganizationPersonsClient.java
- cristin-person/src/test/java/no/unit/nva/cristin/person/handler/ListCristinOrganizationPersonsHandlerTest.java
refactor some redundant test code
> np-41737: fix tests running live

- .github/workflows/karate.yml
- docs/cristin-proxy-swagger.yaml
- template.yaml
Landed on a 5 minute cache of the following endpoints:
* fetchOrganizationByIdentifier
* fetchPersonByIdentifier
* fetchBiobankByIdentifier
* listFundingSources
* fetchFundingSourceByIdentifier
> added caching

- cristin-commons/src/main/java/no/unit/nva/model/adapter/CristinTypedLabelToNvaFormat.java
- cristin-commons/src/main/java/no/unit/nva/model/adapter/TypedLabelToCristinFormat.java
- cristin-keyword/src/main/java/no/unit/nva/cristin/keyword/KeywordConstants.java
- cristin-keyword/src/main/java/no/unit/nva/cristin/keyword/create/CreateKeywordApiClient.java
- cristin-keyword/src/main/java/no/unit/nva/cristin/keyword/create/CreateKeywordHandler.java
- cristin-keyword/src/main/java/no/unit/nva/cristin/keyword/create/CreateKeywordHandlerAccessCheck.java
- cristin-keyword/src/main/java/no/unit/nva/cristin/keyword/create/CristinCreateKeywordApiClient.java
- cristin-keyword/src/main/java/no/unit/nva/cristin/keyword/create/CristinCreateKeywordValidator.java
- cristin-keyword/src/main/java/no/unit/nva/cristin/keyword/query/QueryKeywordsApiClient.java
- cristin-keyword/src/test/java/no/unit/nva/cristin/keyword/create/CreateKeywordHandlerTest.java
- docs/cristin-proxy-swagger.yaml
- template.yaml
with validation and access verification
> Np 46297 post keywords

- cristin-commons/src/main/java/no/unit/nva/cristin/common/handler/CristinQueryHandler.java
- docs/cristin-proxy-swagger.yaml
Excplicit set ecplode: false for query parameters that do not support multiple listings (/users?id=3&id=4&id=5)
https://swagger.io/docs/specification/serialization/
> external-style

- cristin-biobank/build.gradle
- cristin-biobank/src/main/java/no/unit/nva/biobank/client/CristinBiobankApiClient.java
- cristin-biobank/src/main/java/no/unit/nva/biobank/fetch/FetchBiobankHandler.java
- cristin-biobank/src/main/java/no/unit/nva/biobank/model/cristin/CristinAssociatedProject.java
- cristin-biobank/src/main/java/no/unit/nva/biobank/model/cristin/CristinBiobank.java
- cristin-biobank/src/main/java/no/unit/nva/biobank/model/cristin/CristinBiobankMaterial.java
- cristin-biobank/src/main/java/no/unit/nva/biobank/model/cristin/adapter/CristinBiobankToBiobank.java
- cristin-biobank/src/main/java/no/unit/nva/biobank/model/nva/AssociatedProject.java
- cristin-biobank/src/main/java/no/unit/nva/biobank/model/nva/Biobank.java
- cristin-biobank/src/main/java/no/unit/nva/biobank/model/nva/BiobankApproval.java
- cristin-biobank/src/test/java/no/unit/nva/cristin/biobank/fetch/FetchBiobankHandlerTest.java
- cristin-biobank/src/test/resources/nvaApiBiobank1.json
- cristin-biobank/src/test/resources/nvaApiBiobank2.json
Refactor and tidy up biobank module. Add some json testdata for validation. A lot of the lines are json testdata files
> Np 47035 improve old biobank code

- cristin-commons/src/main/java/no/unit/nva/common/IdCreatedLogger.java
- cristin-commons/src/main/java/no/unit/nva/utils/AccessUtils.java
- cristin-funding/src/main/java/no/unit/nva/cristin/funding/sources/client/CristinFundingSourcesApiClient.java
- cristin-funding/src/main/java/no/unit/nva/cristin/funding/sources/fetch/FetchFundingSourceHandler.java
- cristin-funding/src/main/java/no/unit/nva/cristin/funding/sources/query/ListFundingSourcesHandler.java
- cristin-funding/src/test/java/no/unit/nva/cristin/funding/sources/fetch/fetchFundingSource.feature
- cristin-keyword/src/main/java/no/unit/nva/cristin/keyword/query/QueryKeywordsHandler.java
- cristin-organization/src/main/java/no/unit/nva/cristin/organization/common/client/v20230526/OrganizationEnricher.java
> Np 47035 refactor old code nr2

- cristin-commons/src/main/java/no/unit/nva/cristin/model/CristinDateInfo.java
- cristin-project/src/main/java/no/unit/nva/cristin/projects/model/cristin/CristinFundingAmount.java
- cristin-project/src/main/java/no/unit/nva/cristin/projects/model/nva/NvaProjectBuilder.java
Some small improvements by using Optionals and changing classes to records
> Np 47035 small project improvements

- cristin-person/src/main/java/no/unit/nva/cristin/person/create/CreateCristinPersonHandler.java
- cristin-person/src/main/java/no/unit/nva/cristin/person/fetch/FetchFromIdentityNumberHandler.java
- cristin-person/src/main/java/no/unit/nva/cristin/person/model/nva/Binary.java
- cristin-person/src/main/java/no/unit/nva/cristin/person/model/nva/PersonInstitutionInfo.java
- cristin-person/src/main/java/no/unit/nva/cristin/person/model/nva/Role.java
- cristin-person/src/main/java/no/unit/nva/cristin/person/model/nva/TypedValue.java
- cristin-person/src/main/java/no/unit/nva/cristin/person/model/nva/adapter/PersonToCristinFormat.java
- cristin-person/src/main/java/no/unit/nva/cristin/person/picture/update/UpdatePictureContentVerifier.java
- cristin-person/src/main/java/no/unit/nva/cristin/person/update/CristinPersonPatchJsonCreator.java
- cristin-person/src/test/java/no/unit/nva/cristin/person/fetch/FetchCristinPersonHandlerTest.java
- cristin-person/src/test/java/no/unit/nva/cristin/person/picture/fetch/FetchPictureHandlerTest.java
Person classes changed to records where the conversion is easy
> np-47035: use records in person module when it is an easy conversion

- cristin-project/src/test/java/no/unit/nva/cristin/projects/fetch/project.feature
Added and fixed some test coverage to match the new changes in cristin
> Noissue test cristin release 2 18

- README.md
- docs/cristin-proxy-swagger.yaml
Just doing some docs maintenance and update
> Np 47999 update openapi
